name: "E2E: Run tests"

on:
  workflow_call:
    inputs:
      suite_name:
        description: 'Test suite name to run'
        default: 'regression'
        required: true
        type: string
      sha:
        required: true
        type: string

permissions:
  contents: read
  checks: write
  statuses: write

jobs:
  reports:
    runs-on: ubuntu-latest
    #if: ${{ !cancelled() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT

      - name: Download allure reports artifact
        uses: actions/download-artifact@v4
        with:
          name: reports
          path: ./e2e-tests/target/allure-results

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1.9
        id: allure-report
        with:
          allure_results: ./e2e-tests/target/allure-results
          gh_pages: allure-results
          allure_report: allure-report
          subfolder: allure-results
          report_url: "https://reports.kafbat.dev"

      - name: Upload allure report to R2
        uses: ryand56/r2-upload-action@latest
        with:
          source-dir: allure-history/allure-results
          destination-dir: .
          r2-bucket: "reports"
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_ACCESS_SECRET_KEY }}

      - name: Add allure link status check
        uses: Sibz/github-status-action@v1.1.6
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "Click Details button to view Allure report"
          state: "success"
          sha: ${{ inputs.sha }}
          target_url: https://reports.kafbat.dev/${{ github.run_number }}
